spring:
  jpa.hibernate.ddl-auto: none
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  redis:
    host: 'localhost'
    port: 6379
  jpa:
    generate-ddl: true
    show-sql: true
  session.store-type: redis
  datasource:
    url: "jdbc:mysql://localhost:3306/packtdb"
    username: "packt"
    password: "superSecret"

server.port: 9090
