spring:
  jpa.hibernate.ddl-auto: none
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  redis:
    host: 'localhost'
    port: 6379
  jpa:
    generate-ddl: true
    show-sql: true
  application.name: 'bookmarks'
  session.store-type: redis

server.port: 9090
management:
  context-path: '/internal'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
