spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/packtdb"
    username: "packt"
    password: "superSecret"

eureka:
  instance:
    metadata-map:
      user.name: actuator
      user.password: secret
