
management:
  server:
    servlet.context-path: '/internal'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    username: 'packt'
    password: 'publishing'
    addresses: localhost:5672
server:
  use-forward-headers: true