
management:
  context-path: '/internal'
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  rabbitmq:
    username: 'packt'
    password: 'publishing'
    addresses: localhost:5672
