version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.7-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "packt"
      RABBITMQ_DEFAULT_PASS: "publishing"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9410:9410"
      - "9411:9411"
    links:
      - rabbitmq
    environment:
      RABBIT_URI: "amqp://packt:publishing@rabbitmq:5672"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    depends_on:
      - redis
    ports:
      - "8081:8081"
  mysqlbm:
    image: mysql:8.0
    security_opt:
      - seccomp=unconfined
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "packtdb"
      MYSQL_USER: "packt"
      MYSQL_PASSWORD: "superSecret"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "superDuperSecret"
  mysqlus:
     image: mysql:8.0
     security_opt:
       - seccomp=unconfined
     ports:
       - "3307:3306"
     environment:
       MYSQL_DATABASE: "packtdb"
       MYSQL_USER: "packt"
       MYSQL_PASSWORD: "superSecret"
       MYSQL_ROOT_HOST: "%"
       MYSQL_ROOT_PASSWORD: "superDuperSecret"
  mysqlra:
    image: mysql:8.0
    security_opt:
      - seccomp=unconfined
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "packtdb"
      MYSQL_USER: "packt"
      MYSQL_PASSWORD: "superSecret"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "superDuperSecret"